collections:
  authors:
    output: true
  publications:

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:path/